simulation = "SimulatedPricePath"
output_directory = "analysis/prices"
output_file_name = "output"

[trajectory]
# The type of price process to use.
process = "gbm"
# The number of steps in the process.
num_steps = 36500
# Starting seed for the price processes
seed = 10
# The number of distinct paths to use
num_paths = 10
# The initial price of the asset.
initial_price = 1.0
# The start time of the process.
t_0 = 0.0
# The end time of the process.
t_n = 10.0

[gbm]
# The drift of the process.
drift = 0.0
# The volatility of the process.
volatility = 0.5

[block]
timestep_size = 15
